import React from "react";

export const Services = () =>{
return(
    <div><h1>Szolgáltatások</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis veniam repellat fuga porro accusantium nemo, incidunt, ab similique eligendi natus impedit ducimus eveniet sapiente? Inventore iusto reiciendis sapiente. Modi, dolore dolorum! Vel, eum dolor doloribus assumenda necessitatibus, quibusdam eveniet, error incidunt hic voluptates in alias. Possimus distinctio iure provident atque! Quia aspernatur doloremque commodi voluptatibus non nam necessitatibus enim cum consectetur sapiente nulla dolor, natus repellendus blanditiis exercitationem ut reiciendis nobis eligendi quam fuga ea quaerat, eius cupiditate quisquam. Minima reprehenderit iusto, distinctio odio natus ipsum nesciunt quisquam nihil nostrum illum impedit doloribus quia eaque temporibus, ratione illo itaque eveniet.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis veniam repellat fuga porro accusantium nemo, incidunt, ab similique eligendi natus impedit ducimus eveniet sapiente? Inventore iusto reiciendis sapiente. Modi, dolore dolorum! Vel, eum dolor doloribus assumenda necessitatibus, quibusdam eveniet, error incidunt hic voluptates in alias. Possimus distinctio iure provident atque! Quia aspernatur doloremque commodi voluptatibus non nam necessitatibus enim cum consectetur sapiente nulla dolor, natus repellendus blanditiis exercitationem ut reiciendis nobis eligendi quam fuga ea quaerat, eius cupiditate quisquam. Minima reprehenderit iusto, distinctio odio natus ipsum nesciunt quisquam nihil nostrum illum impedit doloribus quia eaque temporibus, ratione illo itaque eveniet.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis veniam repellat fuga porro accusantium nemo, incidunt, ab similique eligendi natus impedit ducimus eveniet sapiente? Inventore iusto reiciendis sapiente. Modi, dolore dolorum! Vel, eum dolor doloribus assumenda necessitatibus, quibusdam eveniet, error incidunt hic voluptates in alias. Possimus distinctio iure provident atque! Quia aspernatur doloremque commodi voluptatibus non nam necessitatibus enim cum consectetur sapiente nulla dolor, natus repellendus blanditiis exercitationem ut reiciendis nobis eligendi quam fuga ea quaerat, eius cupiditate quisquam. Minima reprehenderit iusto, distinctio odio natus ipsum nesciunt quisquam nihil nostrum illum impedit doloribus quia eaque temporibus, ratione illo itaque eveniet.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis veniam repellat fuga porro accusantium nemo, incidunt, ab similique eligendi natus impedit ducimus eveniet sapiente? Inventore iusto reiciendis sapiente. Modi, dolore dolorum! Vel, eum dolor doloribus assumenda necessitatibus, quibusdam eveniet, error incidunt hic voluptates in alias. Possimus distinctio iure provident atque! Quia aspernatur doloremque commodi voluptatibus non nam necessitatibus enim cum consectetur sapiente nulla dolor, natus repellendus blanditiis exercitationem ut reiciendis nobis eligendi quam fuga ea quaerat, eius cupiditate quisquam. Minima reprehenderit iusto, distinctio odio natus ipsum nesciunt quisquam nihil nostrum illum impedit doloribus quia eaque temporibus, ratione illo itaque eveniet.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis veniam repellat fuga porro accusantium nemo, incidunt, ab similique eligendi natus impedit ducimus eveniet sapiente? Inventore iusto reiciendis sapiente. Modi, dolore dolorum! Vel, eum dolor doloribus assumenda necessitatibus, quibusdam eveniet, error incidunt hic voluptates in alias. Possimus distinctio iure provident atque! Quia aspernatur doloremque commodi voluptatibus non nam necessitatibus enim cum consectetur sapiente nulla dolor, natus repellendus blanditiis exercitationem ut reiciendis nobis eligendi quam fuga ea quaerat, eius cupiditate quisquam. Minima reprehenderit iusto, distinctio odio natus ipsum nesciunt quisquam nihil nostrum illum impedit doloribus quia eaque temporibus, ratione illo itaque eveniet.</p>

    </div>
)
};